testZlib:testZlib.cpp 
	g++ -std=c++0x $^ -o $@ -lpthread -lboost_filesystem -lboost_system -lz -lssl -lcrypto -g
server:server.cpp 
	g++ -std=c++0x $^ -o $@ -lpthread -lboost_filesystem -lboost_system -lz -lssl -lcrypto -g
testZlib:testZlib.cpp 
	g++ -std=c++0x $^ -o $@ -lpthread -lboost_filesystem -lboost_system -lz -lssl -lcrypto -g

